In [5]:
import torch
import torch.nn as nn

In [6]:
inputs = torch.tensor([[[0.2, 0.1, 0.3], [0.5, 0.1, 0.1]], [[0.2, 0.1, 0.3], [0.5, 0.1, 0.1]]])
B, S, E = inputs.size()
inputs = inputs.reshape(S, B, E)
inputs.size()

torch.Size([2, 2, 3])

In [7]:
parameter_shape = inputs.size()[-2:]
gamma = nn.Parameter(torch.ones(parameter_shape))
beta = nn.Parameter(torch.zeros(parameter_shape))

In [8]:
gamma.size(), beta.size()

(torch.Size([2, 3]), torch.Size([2, 3]))

In [9]:
dims = [-(i+1) for i in range(len(parameter_shape))]
dims

[-1, -2]

In [10]:
mean = inputs.mean(dim=dims, keepdim = True)
mean

tensor([[[0.2167]],

        [[0.2167]]])

In [11]:
var = ((inputs - mean) ** 2).mean(dim=dims, keepdim=True)
epsilon = 1e-5
std = (var + epsilon).sqrt()
std

tensor([[[0.1463]],

        [[0.1463]]])

In [12]:
y = (inputs - mean) / std
y

tensor([[[-0.1139, -0.7975,  0.5697],
         [ 1.9369, -0.7975, -0.7975]],

        [[-0.1139, -0.7975,  0.5697],
         [ 1.9369, -0.7975, -0.7975]]])

In [13]:
out = gamma * y + beta
out

tensor([[[-0.1139, -0.7975,  0.5697],
         [ 1.9369, -0.7975, -0.7975]],

        [[-0.1139, -0.7975,  0.5697],
         [ 1.9369, -0.7975, -0.7975]]], grad_fn=<AddBackward0>)